"""initial service schema

Revision ID: 3d6450d37a15
Revises: 
Create Date: 2026-08-09 08:51:11.000108

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3d6450d37a15'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alias_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('alias', sa.String(length=512), nullable=False),
    sa.Column('artifact_id', sa.String(length=512), nullable=False),
    sa.Column('previous_artifact_id', sa.String(length=512), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alias_history_alias', 'alias_history', ['alias', 'changed_at'], unique=False)
    op.create_table('api_keys',
    sa.Column('key_id', sa.String(length=64), nullable=False),
    sa.Column('prefix', sa.String(length=16), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('scopes_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('key_id'),
    sa.UniqueConstraint('prefix')
    )
    op.create_index('ix_api_keys_prefix', 'api_keys', ['prefix'], unique=False)
    op.create_index('ix_api_keys_status', 'api_keys', ['status'], unique=False)
    op.create_table('artifacts',
    sa.Column('artifact_id', sa.String(length=512), nullable=False),
    sa.Column('digest_hex', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('logical_name', sa.String(length=512), nullable=False),
    sa.Column('mime_type', sa.String(length=255), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('storage_ref', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('creator', sa.String(length=255), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('schema_version', sa.String(length=16), nullable=False),
    sa.Column('supersedes', sa.String(length=512), nullable=True),
    sa.Column('superseded_by', sa.String(length=512), nullable=True),
    sa.Column('alias', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('artifact_id')
    )
    op.create_index('ix_artifacts_alias', 'artifacts', ['alias'], unique=False)
    op.create_index('ix_artifacts_created_at', 'artifacts', ['created_at'], unique=False)
    op.create_index('ix_artifacts_digest', 'artifacts', ['digest_hex'], unique=False)
    op.create_index('ix_artifacts_kind', 'artifacts', ['kind'], unique=False)
    op.create_index('ix_artifacts_logical_name', 'artifacts', ['logical_name'], unique=False)
    op.create_index('ix_artifacts_status', 'artifacts', ['status'], unique=False)
    op.create_table('attestations',
    sa.Column('attestation_id', sa.String(length=128), nullable=False),
    sa.Column('event_id', sa.String(length=128), nullable=True),
    sa.Column('content_digest', sa.String(length=128), nullable=False),
    sa.Column('signature_json', sa.JSON(), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('attestation_id')
    )
    op.create_table('audit_events',
    sa.Column('sequence', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_hash', sa.String(length=64), nullable=False),
    sa.Column('previous_hash', sa.String(length=64), nullable=True),
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('sequence'),
    sa.UniqueConstraint('event_hash')
    )
    op.create_index('ix_audit_events_type', 'audit_events', ['event_type'], unique=False)
    op.create_table('benchmark_runs',
    sa.Column('run_id', sa.String(length=128), nullable=False),
    sa.Column('preset', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('report_path', sa.Text(), nullable=True),
    sa.Column('manifest_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_index('ix_benchmark_runs_created', 'benchmark_runs', ['created_at'], unique=False)
    op.create_index('ix_benchmark_runs_status', 'benchmark_runs', ['status'], unique=False)
    op.create_table('candidate_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('target_artifact_id', sa.String(length=512), nullable=False),
    sa.Column('candidate_artifact_id', sa.String(length=512), nullable=False),
    sa.Column('raw_score', sa.Float(), nullable=False),
    sa.Column('calibrated_probability', sa.Float(), nullable=True),
    sa.Column('calibration_artifact_id', sa.String(length=512), nullable=True),
    sa.Column('strict_negative', sa.Boolean(), nullable=False),
    sa.Column('feature_breakdown_json', sa.JSON(), nullable=False),
    sa.Column('scorer_version', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_candidate_scores_candidate', 'candidate_scores', ['candidate_artifact_id'], unique=False)
    op.create_index('ix_candidate_scores_target', 'candidate_scores', ['target_artifact_id'], unique=False)
    op.create_table('derivations',
    sa.Column('derivation_id', sa.String(length=128), nullable=False),
    sa.Column('recipe', sa.String(length=255), nullable=False),
    sa.Column('recipe_version', sa.String(length=64), nullable=False),
    sa.Column('target_artifact_id', sa.String(length=512), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('derivation_id')
    )
    op.create_index('ix_derivations_started', 'derivations', ['started_at'], unique=False)
    op.create_index('ix_derivations_target', 'derivations', ['target_artifact_id'], unique=False)
    op.create_table('edges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=512), nullable=False),
    sa.Column('target', sa.String(length=512), nullable=False),
    sa.Column('relation', sa.String(length=64), nullable=False),
    sa.Column('evidence_class', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scorer_version', sa.String(length=32), nullable=True),
    sa.Column('invalidation_reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'target', 'relation', name='uq_edge_triple')
    )
    op.create_index('ix_edges_evidence', 'edges', ['evidence_class'], unique=False)
    op.create_index('ix_edges_source', 'edges', ['source'], unique=False)
    op.create_index('ix_edges_status', 'edges', ['status'], unique=False)
    op.create_index('ix_edges_target', 'edges', ['target'], unique=False)
    op.create_table('idempotency_records',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('operation_scope', sa.String(length=128), nullable=False),
    sa.Column('request_digest', sa.String(length=64), nullable=False),
    sa.Column('response_reference', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index('ix_idempotency_scope', 'idempotency_records', ['operation_scope'], unique=False)
    op.create_table('installations',
    sa.Column('installation_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('schema_version', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('installation_id')
    )
    op.create_table('job_events',
    sa.Column('event_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index('ix_job_events_job', 'job_events', ['job_id', 'event_id'], unique=False)
    op.create_table('jobs',
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lease_owner', sa.String(length=128), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('progress_current', sa.Integer(), nullable=False),
    sa.Column('progress_total', sa.Integer(), nullable=True),
    sa.Column('progress_message', sa.Text(), nullable=True),
    sa.Column('result_reference', sa.String(length=512), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('sanitized_error', sa.Text(), nullable=True),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('actor_id', sa.String(length=255), nullable=True),
    sa.Column('cancellation_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('job_id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index('ix_jobs_lease_expires', 'jobs', ['lease_expires_at'], unique=False)
    op.create_index('ix_jobs_scheduled', 'jobs', ['scheduled_at'], unique=False)
    op.create_index('ix_jobs_status_priority', 'jobs', ['status', 'priority'], unique=False)
    op.create_table('quarantine',
    sa.Column('artifact_id', sa.String(length=512), nullable=False),
    sa.Column('revocation_event_id', sa.String(length=128), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('artifact_id')
    )
    op.create_index('ix_quarantine_active', 'quarantine', ['active'], unique=False)
    op.create_table('rebuild_attempts',
    sa.Column('attempt_id', sa.String(length=128), nullable=False),
    sa.Column('plan_id', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('successor_artifact_id', sa.String(length=512), nullable=True),
    sa.Column('verification_report_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('attempt_id')
    )
    op.create_index('ix_rebuild_attempts_plan', 'rebuild_attempts', ['plan_id'], unique=False)
    op.create_table('rebuild_plans',
    sa.Column('plan_id', sa.String(length=128), nullable=False),
    sa.Column('revocation_event_id', sa.String(length=128), nullable=True),
    sa.Column('target_artifact_id', sa.String(length=512), nullable=False),
    sa.Column('plan_digest', sa.String(length=128), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('plan_id')
    )
    op.create_table('replay_records',
    sa.Column('replay_id', sa.String(length=128), nullable=False),
    sa.Column('target_derivation_id', sa.String(length=128), nullable=False),
    sa.Column('candidate_ancestor_id', sa.String(length=512), nullable=False),
    sa.Column('intervention_kind', sa.String(length=64), nullable=False),
    sa.Column('runner_id', sa.String(length=128), nullable=True),
    sa.Column('verdict', sa.String(length=32), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('replay_id')
    )
    op.create_index('ix_replay_candidate', 'replay_records', ['candidate_ancestor_id'], unique=False)
    op.create_index('ix_replay_status', 'replay_records', ['verdict'], unique=False)
    op.create_index('ix_replay_target', 'replay_records', ['target_derivation_id'], unique=False)
    op.create_table('revocation_events',
    sa.Column('event_id', sa.String(length=128), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=64), nullable=False),
    sa.Column('policy', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('event_id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index('ix_revocation_created', 'revocation_events', ['created_at'], unique=False)
    op.create_index('ix_revocation_state', 'revocation_events', ['state'], unique=False)
    op.create_table('revocation_transitions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(length=128), nullable=False),
    sa.Column('from_state', sa.String(length=64), nullable=True),
    sa.Column('to_state', sa.String(length=64), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transitions_event', 'revocation_transitions', ['event_id'], unique=False)
    op.create_table('verification_reports',
    sa.Column('report_id', sa.String(length=128), nullable=False),
    sa.Column('artifact_id', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_table('waivers',
    sa.Column('waiver_id', sa.String(length=128), nullable=False),
    sa.Column('artifact_id', sa.String(length=512), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('scope', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revocation_event_id', sa.String(length=128), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('waiver_id')
    )
    op.create_index('ix_waivers_artifact', 'waivers', ['artifact_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_waivers_artifact', table_name='waivers')
    op.drop_table('waivers')
    op.drop_table('verification_reports')
    op.drop_index('ix_transitions_event', table_name='revocation_transitions')
    op.drop_table('revocation_transitions')
    op.drop_index('ix_revocation_state', table_name='revocation_events')
    op.drop_index('ix_revocation_created', table_name='revocation_events')
    op.drop_table('revocation_events')
    op.drop_index('ix_replay_target', table_name='replay_records')
    op.drop_index('ix_replay_status', table_name='replay_records')
    op.drop_index('ix_replay_candidate', table_name='replay_records')
    op.drop_table('replay_records')
    op.drop_table('rebuild_plans')
    op.drop_index('ix_rebuild_attempts_plan', table_name='rebuild_attempts')
    op.drop_table('rebuild_attempts')
    op.drop_index('ix_quarantine_active', table_name='quarantine')
    op.drop_table('quarantine')
    op.drop_index('ix_jobs_status_priority', table_name='jobs')
    op.drop_index('ix_jobs_scheduled', table_name='jobs')
    op.drop_index('ix_jobs_lease_expires', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index('ix_job_events_job', table_name='job_events')
    op.drop_table('job_events')
    op.drop_table('installations')
    op.drop_index('ix_idempotency_scope', table_name='idempotency_records')
    op.drop_table('idempotency_records')
    op.drop_index('ix_edges_target', table_name='edges')
    op.drop_index('ix_edges_status', table_name='edges')
    op.drop_index('ix_edges_source', table_name='edges')
    op.drop_index('ix_edges_evidence', table_name='edges')
    op.drop_table('edges')
    op.drop_index('ix_derivations_target', table_name='derivations')
    op.drop_index('ix_derivations_started', table_name='derivations')
    op.drop_table('derivations')
    op.drop_index('ix_candidate_scores_target', table_name='candidate_scores')
    op.drop_index('ix_candidate_scores_candidate', table_name='candidate_scores')
    op.drop_table('candidate_scores')
    op.drop_index('ix_benchmark_runs_status', table_name='benchmark_runs')
    op.drop_index('ix_benchmark_runs_created', table_name='benchmark_runs')
    op.drop_table('benchmark_runs')
    op.drop_index('ix_audit_events_type', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_table('attestations')
    op.drop_index('ix_artifacts_status', table_name='artifacts')
    op.drop_index('ix_artifacts_logical_name', table_name='artifacts')
    op.drop_index('ix_artifacts_kind', table_name='artifacts')
    op.drop_index('ix_artifacts_digest', table_name='artifacts')
    op.drop_index('ix_artifacts_created_at', table_name='artifacts')
    op.drop_index('ix_artifacts_alias', table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_index('ix_api_keys_status', table_name='api_keys')
    op.drop_index('ix_api_keys_prefix', table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index('ix_alias_history_alias', table_name='alias_history')
    op.drop_table('alias_history')
    # ### end Alembic commands ###
