"""derivation lineage evidence and candidate recovery

Revision ID: b29242c5289a
Revises: 3d6450d37a15
Create Date: 2026-08-09 12:01:23.800836

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b29242c5289a'
down_revision: Union[str, Sequence[str], None] = '3d6450d37a15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_scoring_runs',
    sa.Column('run_id', sa.String(length=128), nullable=False),
    sa.Column('request_key', sa.String(length=255), nullable=False),
    sa.Column('root_artifact_id', sa.String(length=512), nullable=False),
    sa.Column('candidate_scope_json', sa.JSON(), nullable=False),
    sa.Column('feature_config_json', sa.JSON(), nullable=False),
    sa.Column('threshold_config_json', sa.JSON(), nullable=False),
    sa.Column('scorer_version', sa.String(length=32), nullable=False),
    sa.Column('config_digest', sa.String(length=64), nullable=False),
    sa.Column('snapshot_digest', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=True),
    sa.Column('candidates_considered', sa.Integer(), nullable=False),
    sa.Column('candidates_found', sa.Integer(), nullable=False),
    sa.Column('checkpoint_index', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('run_id'),
    sa.UniqueConstraint('request_key')
    )
    op.create_index('ix_candidate_runs_root', 'candidate_scoring_runs', ['root_artifact_id'], unique=False)
    op.create_index('ix_candidate_runs_status', 'candidate_scoring_runs', ['status'], unique=False)
    op.create_table('derivation_inputs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('derivation_id', sa.String(length=128), nullable=False),
    sa.Column('parent_artifact_id', sa.String(length=512), nullable=False),
    sa.Column('relation', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('derivation_id', 'parent_artifact_id', 'relation', name='uq_derivation_input')
    )
    op.create_index('ix_derivation_inputs_derivation', 'derivation_inputs', ['derivation_id'], unique=False)
    op.create_index('ix_derivation_inputs_parent', 'derivation_inputs', ['parent_artifact_id'], unique=False)
    op.create_table('feature_observations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_artifact_id', sa.String(length=512), nullable=False),
    sa.Column('target_artifact_id', sa.String(length=512), nullable=False),
    sa.Column('feature_family', sa.String(length=32), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('extractor_version', sa.String(length=64), nullable=False),
    sa.Column('config_digest', sa.String(length=64), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_artifact_id', 'target_artifact_id', 'feature_family', 'extractor_version', 'config_digest', name='uq_feature_observation')
    )
    op.create_index('ix_feature_observations_pair', 'feature_observations', ['source_artifact_id', 'target_artifact_id'], unique=False)
    # batch mode: SQLite (used by this repository's own migration tests, see
    # migrations/env.py) cannot ALTER a table to add a constraint in place;
    # batch mode does a copy-and-move under the hood on SQLite and a plain
    # ALTER on PostgreSQL, so this is portable across both dialects.
    with op.batch_alter_table('candidate_scores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('run_id', sa.String(length=128), nullable=True))
        batch_op.add_column(
            sa.Column('evidence_class', sa.String(length=32), nullable=False, server_default='inferred')
        )
        batch_op.add_column(sa.Column('status', sa.String(length=32), nullable=False, server_default='candidate'))
        batch_op.add_column(sa.Column('explanation_text', sa.Text(), nullable=True))
        batch_op.add_column(
            sa.Column('inclusion_reasons_json', sa.JSON(), nullable=False, server_default='[]')
        )
        batch_op.create_index('ix_candidate_scores_run', ['run_id'], unique=False)
        batch_op.create_unique_constraint(
            'uq_candidate_score_run_candidate', ['run_id', 'candidate_artifact_id']
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate_scores', schema=None) as batch_op:
        batch_op.drop_constraint('uq_candidate_score_run_candidate', type_='unique')
        batch_op.drop_index('ix_candidate_scores_run')
        batch_op.drop_column('inclusion_reasons_json')
        batch_op.drop_column('explanation_text')
        batch_op.drop_column('status')
        batch_op.drop_column('evidence_class')
        batch_op.drop_column('run_id')
    op.drop_index('ix_feature_observations_pair', table_name='feature_observations')
    op.drop_table('feature_observations')
    op.drop_index('ix_derivation_inputs_parent', table_name='derivation_inputs')
    op.drop_index('ix_derivation_inputs_derivation', table_name='derivation_inputs')
    op.drop_table('derivation_inputs')
    op.drop_index('ix_candidate_runs_status', table_name='candidate_scoring_runs')
    op.drop_index('ix_candidate_runs_root', table_name='candidate_scoring_runs')
    op.drop_table('candidate_scoring_runs')
    # ### end Alembic commands ###
