"""service replay evidence and promotion

Revision ID: de2e581d5efc
Revises: b29242c5289a
Create Date: 2026-08-09 12:27:53.980865

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'de2e581d5efc'
down_revision: Union[str, Sequence[str], None] = 'b29242c5289a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('replay_runs',
    sa.Column('replay_run_id', sa.String(length=128), nullable=False),
    sa.Column('request_key', sa.String(length=255), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('ancestor_artifact_id', sa.String(length=512), nullable=False),
    sa.Column('descendant_artifact_id', sa.String(length=512), nullable=False),
    sa.Column('target_derivation_id', sa.String(length=128), nullable=True),
    sa.Column('runner_name', sa.String(length=64), nullable=False),
    sa.Column('repetitions_requested', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=True),
    sa.Column('checkpoint_repetition', sa.Integer(), nullable=False),
    sa.Column('verdict', sa.String(length=32), nullable=True),
    sa.Column('fidelity_overall', sa.Float(), nullable=True),
    sa.Column('effect_estimate', sa.Float(), nullable=True),
    sa.Column('created_by_actor', sa.String(length=255), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('replay_run_id'),
    sa.UniqueConstraint('request_key')
    )
    op.create_index('ix_replay_runs_actor', 'replay_runs', ['created_by_actor'], unique=False)
    op.create_index('ix_replay_runs_candidate', 'replay_runs', ['candidate_id'], unique=False)
    op.create_index('ix_replay_runs_status', 'replay_runs', ['status'], unique=False)
    with op.batch_alter_table('candidate_scores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latest_replay_run_id', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('latest_replay_verdict', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('latest_replay_at', sa.DateTime(timezone=True), nullable=True))
    # batch mode: SQLite (used by this repository's own migration tests, see
    # migrations/env.py) cannot ALTER a table to add a constraint in place;
    # batch mode does a copy-and-move under the hood on SQLite and a plain
    # ALTER on PostgreSQL, so this is portable across both dialects.
    with op.batch_alter_table('replay_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('replay_run_id', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('repetition_index', sa.Integer(), nullable=True))
        batch_op.create_index('ix_replay_run', ['replay_run_id'], unique=False)
        batch_op.create_unique_constraint('uq_replay_run_repetition', ['replay_run_id', 'repetition_index'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('replay_records', schema=None) as batch_op:
        batch_op.drop_constraint('uq_replay_run_repetition', type_='unique')
        batch_op.drop_index('ix_replay_run')
        batch_op.drop_column('repetition_index')
        batch_op.drop_column('replay_run_id')
    with op.batch_alter_table('candidate_scores', schema=None) as batch_op:
        batch_op.drop_column('latest_replay_at')
        batch_op.drop_column('latest_replay_verdict')
        batch_op.drop_column('latest_replay_run_id')
    op.drop_index('ix_replay_runs_status', table_name='replay_runs')
    op.drop_index('ix_replay_runs_candidate', table_name='replay_runs')
    op.drop_index('ix_replay_runs_actor', table_name='replay_runs')
    op.drop_table('replay_runs')
    # ### end Alembic commands ###
